spring.application.name=Vjezba_7_Sping_data_jpa
## URL for in-memory database
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## Enable H2 web console at localhost:8082/h2-console
#spring.h2.console.enabled=true
#
#server.port=8081


#spring.sql.init.mode=always
#debug=true

spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;trustServerCertificate=true;encrypt=true;integratedSecurity=false;databaseName=MojaPrvaBaza;
spring.datasource.username=sa
spring.datasource.password=SQL
server.port=8081